server:
  error:
    include-stacktrace: never

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    url: ${JDBC_DATABASE_URL}

#  jpa:
#    show-sql: false
#    hibernate:
#      : update

logging:
  level:
    ROOT: INFO
