server:
  port: ${PORT:5001}

base-url: /api

spring:
  profiles:
    active:  dev

  application:
    name: taskManager


  liquibase:
#    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop

# swagger-ui custom path (optional parameter by default http://server:port/swagger-ui.html)
springdoc:
  swagger-ui:
    path: /swagger-ui.html

rollbar_token: b92e633b71d745e7b3338f482f6c4e6d


