spring:
  profiles:
    active: dev

server:
  port: ${PORT:5001}

logging:
  level:
    root: INFO

base-url: /api

jwt:
  issuer: spring_blog
  expiration-sec: 86400
  clock-skew-sec: 300
  secret: secret

rollbar_token: 2323