spring:
  datasource:
    url: jdbc:h2:./hexlet
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true
